/**
 * TM-89 (ADR-0022 follow-up to TM-84) — persistent asset-gen cache.
 *
 * ADR-0022 mandates `hash(prompt + style + size) → cacheKey` so an
 * image-gen LLM call can be skipped on a cache hit. The original TM-90
 * `asset-gen-stage.ts` only wrote to local `public/uploads/asset-gen/`,
 * which is wiped on every serverless redeploy — so the cache never
 * survived a deploy and the cost-saving promise of ADR-0022 ("캐시 적중
 * 시 후속 편집은 $0.005 유지") was unrealised in production.
 *
 * This module introduces a small `AssetCache` interface with two
 * interchangeable implementations:
 *   - `fsAssetCache`   — local filesystem (default, no credentials needed).
 *   - `r2AssetCache`   — Cloudflare R2 (S3-compatible), env-gated.
 *
 * Provider selection mirrors `src/lib/storage` (TM-31, ADR-0013): the app
 * stays runnable + testable without any external credential, and the R2
 * adapter activates only when its env vars are present.
 *
 * Behaviour contract (do NOT widen without a new ADR):
 *   - `get(cacheKey)`  → cached bytes + public URL, or `null` on miss.
 *   - `put(cacheKey, asset)` → persists bytes, returns the public URL.
 *   - Both are best-effort: an IO/network error on `get` MUST degrade to a
 *     miss (return null) rather than throw, so a flaky cache can never block
 *     image generation. `put` errors propagate so the caller can log, but
 *     the stage still returns the freshly generated bytes.
 */

/** A cached image asset. */
export interface CachedAsset {
  /** Public URL the scene-code stage can splice into `<Img src=... />`. */
  url: string;
  /** Raw PNG bytes — present on a cache hit so callers can re-persist/inspect. */
  bytes: Buffer;
  /** Identifier of the cache backend that served this hit (telemetry). */
  provider: string;
}

export interface PutAssetInput {
  /** sha256 cache key (see `hashAssetGenInputs`). */
  cacheKey: string;
  /** Raw PNG bytes to persist. */
  bytes: Buffer;
  /** Content type — defaults to image/png. */
  contentType?: string;
}

export interface AssetCache {
  /** Backend identifier, e.g. "fs" | "r2". */
  readonly name: string;
  /**
   * Look up a cache key. Returns the cached asset on a hit, or `null` on a
   * miss. MUST NOT throw for transport/IO errors — degrade to a miss so
   * generation can proceed.
   */
  get(cacheKey: string): Promise<CachedAsset | null>;
  /**
   * Persist bytes under `cacheKey`. Returns the public URL. May throw on a
   * hard failure (caller logs but still serves the generated bytes).
   */
  put(input: PutAssetInput): Promise<string>;
}
