/**
 * TM-175 — lucide whitelist snapshot sync guard.
 *
 * The in-app validator (`src/lib/lucide-whitelist.ts`) introspects
 * `lucide-react` live, while the MCP plugin
 * (`plugin/remotion-eval/src/validate.ts`) reads a JSON snapshot at
 * `plugin/remotion-eval/src/lucide-whitelist.json` (regenerated by
 * `scripts/codegen/lucide-whitelist-snapshot.mjs`).
 *
 * The two MUST stay in sync — drift means external agents pre-flighting
 * via the MCP server may accept icons the in-app evaluator will reject
 * (or vice-versa), reintroducing the very `<Unknown>` ErrorBoundary
 * residue this work eliminated.
 *
 * This test compares the snapshot set against `Object.keys(lucide-react)`
 * filtered to PascalCase, and fails — with the diff size — on any
 * mismatch. Remediation: run
 *
 *     node scripts/codegen/lucide-whitelist-snapshot.mjs
 *
 * and commit the regenerated JSON.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { LUCIDE_VALID_NAMES } from '@/lib/lucide-whitelist';

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const SNAPSHOT_PATH = path.join(
  REPO_ROOT,
  'plugin',
  'remotion-eval',
  'src',
  'lucide-whitelist.json',
);

describe('TM-175 — lucide-whitelist snapshot sync (in-app ↔ MCP plugin)', () => {
  it('snapshot JSON exists', () => {
    expect(fs.existsSync(SNAPSHOT_PATH)).toBe(true);
  });

  it('snapshot set equals live lucide-react exports', () => {
    const raw = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf8')) as {
      names: string[];
    };
    const snapshot = new Set(raw.names);
    const live = LUCIDE_VALID_NAMES;

    const missing: string[] = [];
    for (const n of live) {
      if (!snapshot.has(n)) missing.push(n);
    }
    const extra: string[] = [];
    for (const n of snapshot) {
      if (!live.has(n)) extra.push(n);
    }

    if (missing.length > 0 || extra.length > 0) {
      throw new Error(
        `lucide-whitelist drift between live import and snapshot JSON.\n` +
          `Run: node scripts/codegen/lucide-whitelist-snapshot.mjs\n\n` +
          `Missing from snapshot (present in live): ${missing.slice(0, 10).join(', ')}${missing.length > 10 ? `… +${missing.length - 10}` : ''}\n` +
          `Extra in snapshot (not in live): ${extra.slice(0, 10).join(', ')}${extra.length > 10 ? `… +${extra.length - 10}` : ''}`,
      );
    }

    expect(snapshot.size).toBe(live.size);
  });
});
